---
      - name: restart apache
        service:
            name: httpd
            state: restarted

      - name: start zabbix server
        service:
            name: zabbix-server
            state: started
