---
    - name: instalando repo zabbix
      ignore_errors: yes
      yum:
          state: present
          name: "{{ item }}"

      with_items: 
          
            - http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-1.el7.centos.noarch.rpm

    
    - name: Install Zabbix
      ignore_errors: yes
      package:
        name: "{{ item }}"
        state: present
      with_items: 
          - zabbix-get 
          - zabbix-server-mysql 
          - zabbix-web-mysql 
          - zabbix-agent
          
    - name: Extraindo sample DB
      shell: gunzip /usr/share/doc/zabbix-server-mysql-{{ zabbix_mysql_version }}/create.sql.gz
      ignore_errors: yes

    - name: Importando sample zabbix
      mysql_db:
          name: zabbix
          state: import
          target: /usr/share/doc/zabbix-server-mysql-{{ zabbix_mysql_version }}/create.sql
      ignore_errors: yes

    - name: Aplicando template de Conf do zabbix
      template: 
        src: templates/zabbix_server.conf.j2
        dest: /etc/zabbix/zabbix_server.conf
      notify: 
          - start zabbix server
          - restart apache

  
